import { DrinkPreset } from "./types";

/**
 * Volumenes y graduaciones de referencia (promedios de mercado / catedra).
 * Todo es editable en la app: son puntos de partida para no tener que recordar
 * ni calcular nada de memoria. En los tragos preparados, "baseRatio" es la
 * fraccion del vaso que es bebida alcoholica (el resto es hielo/gaseosa/jugo).
 */

const SHORT_LONG = [
  { id: "corto", label: "Vaso trago corto", volumeMl: 250 },
  { id: "largo", label: "Vaso trago largo", volumeMl: 400 },
];
const COPA = [
  { id: "copa", label: "Copa", volumeMl: 200 },
  { id: "copa-grande", label: "Copa grande", volumeMl: 250 },
];

export const DRINKS: DrinkPreset[] = [
  // ---------- Fermentadas ----------
  {
    id: "vino",
    name: "Vino",
    category: "fermentada",
    icon: "wine",
    defaultAbv: 12.5,
    color: "#9d2249",
    measures: [
      { id: "copa-chica", label: "Copa chica", volumeMl: 150 },
      { id: "copa", label: "Copa", volumeMl: 200 },
      { id: "media-botella", label: "Media botella", volumeMl: 375 },
      { id: "botella", label: "Botella", volumeMl: 750 },
    ],
  },
  {
    id: "cerveza",
    name: "Cerveza",
    category: "fermentada",
    icon: "beer",
    defaultAbv: 5,
    color: "#d99a2b",
    measures: [
      { id: "porron", label: "Porron", volumeMl: 250 },
      { id: "botella", label: "Botella", volumeMl: 340 },
      { id: "pinta", label: "Pinta", volumeMl: 500 },
      { id: "litro", label: "Litro (para compartir)", volumeMl: 1000 },
    ],
  },
  {
    id: "sidra",
    name: "Sidra",
    category: "fermentada",
    icon: "cider",
    defaultAbv: 5.5,
    color: "#c9d14a",
    measures: [
      { id: "copa", label: "Copa", volumeMl: 100 },
      { id: "copa-grande", label: "Copa grande", volumeMl: 200 },
      { id: "botella", label: "Botella", volumeMl: 750 },
    ],
  },
  {
    id: "sake",
    name: "Sake",
    category: "fermentada",
    icon: "sake",
    defaultAbv: 15,
    color: "#e6e2d3",
    measures: [
      { id: "copa", label: "Copa", volumeMl: 100 },
      { id: "copa-grande", label: "Copa grande", volumeMl: 150 },
    ],
  },
  {
    id: "hidromiel",
    name: "Hidromiel",
    category: "fermentada",
    icon: "mead",
    defaultAbv: 8,
    color: "#d4a017",
    measures: [
      { id: "vaso", label: "Vaso", volumeMl: 100 },
      { id: "vaso-grande", label: "Vaso grande", volumeMl: 200 },
    ],
  },
  {
    id: "gancia",
    name: "Gancia",
    category: "fermentada",
    icon: "wine",
    defaultAbv: 14.7,
    color: "#c96a3a",
    measures: COPA,
  },

  // ---------- Destiladas ----------
  {
    id: "ginebra",
    name: "Ginebra",
    category: "destilada",
    icon: "gin",
    defaultAbv: 40,
    color: "#4f8a72",
    measures: [
      { id: "trago", label: "Trago", volumeMl: 50 },
      { id: "doble", label: "Doble", volumeMl: 100 },
    ],
  },
  {
    id: "ron",
    name: "Ron",
    category: "destilada",
    icon: "rum",
    defaultAbv: 40,
    color: "#8a5a2b",
    measures: [
      { id: "vaso", label: "Vaso", volumeMl: 60 },
      { id: "doble", label: "Doble", volumeMl: 120 },
    ],
  },
  {
    id: "brandy",
    name: "Brandy",
    category: "destilada",
    icon: "brandy",
    defaultAbv: 36,
    color: "#a5661f",
    measures: [
      { id: "copa", label: "Copa", volumeMl: 50 },
      { id: "doble", label: "Doble", volumeMl: 100 },
    ],
  },
  {
    id: "tequila",
    name: "Tequila",
    category: "destilada",
    icon: "tequila",
    defaultAbv: 38,
    color: "#d8b34a",
    measures: [
      { id: "shot", label: "Shot", volumeMl: 60 },
      { id: "doble", label: "Doble", volumeMl: 120 },
    ],
  },
  {
    id: "whisky",
    name: "Whisky",
    category: "destilada",
    icon: "whisky",
    defaultAbv: 40,
    color: "#9c6b1f",
    measures: [
      { id: "vaso-corto", label: "Vaso corto", volumeMl: 50 },
      { id: "vaso", label: "Vaso", volumeMl: 100 },
      { id: "doble", label: "Doble", volumeMl: 200 },
    ],
  },
  {
    id: "vodka",
    name: "Vodka",
    category: "destilada",
    icon: "vodka",
    defaultAbv: 40,
    color: "#7ea8c4",
    measures: [
      { id: "vaso", label: "Vaso", volumeMl: 50 },
      { id: "doble", label: "Doble", volumeMl: 100 },
    ],
  },
  {
    id: "fernet-solo",
    name: "Fernet (solo)",
    category: "destilada",
    icon: "fernet",
    defaultAbv: 39,
    color: "#3d2b1f",
    measures: [{ id: "vaso", label: "Vaso", volumeMl: 50 }],
  },
  {
    id: "cynar",
    name: "Cynar",
    category: "destilada",
    icon: "fernet",
    defaultAbv: 16.5,
    color: "#2e1c12",
    measures: [
      { id: "vaso", label: "Vaso", volumeMl: 50 },
      { id: "doble", label: "Doble", volumeMl: 100 },
    ],
  },

  // ---------- Tragos preparados ----------
  {
    id: "fernet-cola",
    name: "Fernet con Coca",
    category: "preparado",
    icon: "fernet",
    defaultAbv: 39,
    baseRatio: 0.3,
    color: "#5b3a29",
    measures: SHORT_LONG,
  },
  {
    id: "gin-tonic",
    name: "Gin Tonic",
    category: "preparado",
    icon: "cocktail",
    defaultAbv: 42,
    baseRatio: 0.22,
    color: "#4f8a72",
    measures: SHORT_LONG,
  },
  {
    id: "whisky-cola",
    name: "Whisky con Coca",
    category: "preparado",
    icon: "cocktail",
    defaultAbv: 40,
    baseRatio: 0.25,
    color: "#9c6b1f",
    measures: SHORT_LONG,
  },
  {
    id: "cuba-libre",
    name: "Cuba Libre",
    category: "preparado",
    icon: "cocktail",
    defaultAbv: 40,
    baseRatio: 0.25,
    color: "#6b3a24",
    measures: SHORT_LONG,
  },
  {
    id: "vodka-jugo",
    name: "Vodka con jugo",
    category: "preparado",
    icon: "cocktail",
    defaultAbv: 40,
    baseRatio: 0.2,
    color: "#7ea8c4",
    measures: SHORT_LONG,
  },
  {
    id: "vodka-energizante",
    name: "Vodka con energizante",
    category: "preparado",
    icon: "cocktail",
    defaultAbv: 40,
    baseRatio: 0.3,
    color: "#b5c23a",
    measures: SHORT_LONG,
  },
  {
    id: "aperol-spritz",
    name: "Aperol Spritz",
    category: "preparado",
    icon: "cocktail",
    defaultAbv: 11,
    baseRatio: 0.3,
    color: "#e8712d",
    measures: [{ id: "copa", label: "Copa de vino", volumeMl: 300 }],
  },
  {
    id: "negroni",
    name: "Negroni",
    category: "preparado",
    icon: "cocktail",
    defaultAbv: 26,
    baseRatio: 0.7,
    color: "#a11f2a",
    measures: [{ id: "vaso", label: "Vaso corto con hielo", volumeMl: 120 }],
  },
  {
    id: "mojito",
    name: "Mojito",
    category: "preparado",
    icon: "cocktail",
    defaultAbv: 40,
    baseRatio: 0.2,
    color: "#4faa5a",
    measures: SHORT_LONG,
  },
  {
    id: "caipirinha",
    name: "Caipirinha",
    category: "preparado",
    icon: "cocktail",
    defaultAbv: 40,
    baseRatio: 0.4,
    color: "#8ab24a",
    measures: [{ id: "vaso", label: "Vaso", volumeMl: 250 }],
  },
  {
    id: "daiquiri",
    name: "Daiquiri",
    category: "preparado",
    icon: "cocktail",
    defaultAbv: 40,
    baseRatio: 0.5,
    color: "#e7e2cf",
    measures: [{ id: "copa", label: "Copa", volumeMl: 150 }],
  },
  {
    id: "margarita",
    name: "Margarita",
    category: "preparado",
    icon: "cocktail",
    defaultAbv: 35,
    baseRatio: 0.5,
    color: "#cfe08a",
    measures: [{ id: "copa", label: "Copa", volumeMl: 200 }],
  },
  {
    id: "tequila-sunrise",
    name: "Tequila Sunrise",
    category: "preparado",
    icon: "cocktail",
    defaultAbv: 38,
    baseRatio: 0.2,
    color: "#e8944a",
    measures: SHORT_LONG,
  },
  {
    id: "clerico",
    name: "Clerico",
    category: "preparado",
    icon: "wine",
    defaultAbv: 12.5,
    baseRatio: 0.6,
    color: "#b0304f",
    measures: [
      { id: "copa", label: "Copa", volumeMl: 250 },
      { id: "jarra", label: "Jarra (para compartir)", volumeMl: 1000 },
    ],
  },
  {
    id: "sangria",
    name: "Sangria",
    category: "preparado",
    icon: "wine",
    defaultAbv: 12.5,
    baseRatio: 0.6,
    color: "#8e1f38",
    measures: [
      { id: "copa", label: "Copa", volumeMl: 250 },
      { id: "jarra", label: "Jarra (para compartir)", volumeMl: 1000 },
    ],
  },
  {
    id: "vino-soda",
    name: "Vino con soda",
    category: "preparado",
    icon: "wine",
    defaultAbv: 12.5,
    baseRatio: 0.6,
    color: "#b0455f",
    measures: [{ id: "vaso", label: "Vaso", volumeMl: 250 }],
  },
  {
    id: "michelada",
    name: "Michelada",
    category: "preparado",
    icon: "beer",
    defaultAbv: 5,
    baseRatio: 0.9,
    color: "#d98a2b",
    measures: [{ id: "vaso", label: "Vaso", volumeMl: 400 }],
  },

  // ---------- Otra ----------
  {
    id: "otra",
    name: "Otra bebida",
    category: "otra",
    icon: "custom",
    defaultAbv: 10,
    color: "#8b8b9e",
    measures: [{ id: "personalizada", label: "Volumen personalizado", volumeMl: 200 }],
  },
];

export function getDrink(id: string): DrinkPreset | undefined {
  return DRINKS.find((d) => d.id === id);
}

export const CATEGORY_LABELS: Record<string, string> = {
  fermentada: "Fermentadas",
  destilada: "Destiladas",
  preparado: "Tragos preparados",
  otra: "Otra",
};
